export default function TermsPage() {
  return (
    <div className="container mx-auto px-4 py-32 max-w-3xl">
      <h1 className="text-4xl font-bold mb-8">Terms of Service</h1>
      <div className="prose prose-neutral dark:prose-invert max-w-none">
        <p className="text-muted-foreground mb-6">Last updated: {new Date().toLocaleDateString()}</p>
        
        <h2>1. Acceptance of Terms</h2>
        <p>
          By accessing and using the Tattoo Generator application ("the App"), you accept and agree to be bound by the terms and provision of this agreement.
        </p>

        <h2>2. Description of Service</h2>
        <p>
          The App provides users with AI-powered tools to generate, visualize, and customize tattoo designs. We reserve the right to modify, suspend, or discontinue the service at any time.
        </p>

        <h2>3. User Content</h2>
        <p>
          You retain all rights to any images or content you upload to the App. By uploading content, you grant us a license to use, process, and display that content solely for the purpose of providing the service to you.
        </p>

        <h2>4. Intellectual Property</h2>
        <p>
          The generated designs are provided for your personal use. While you own the specific output generated by your prompts, the underlying AI models and application code remain our property.
        </p>

        <h2>5. Privacy</h2>
        <p>
          Your use of the App is also governed by our Privacy Policy. Please review our Privacy Policy to understand our practices.
        </p>

        <h2>6. Limitation of Liability</h2>
        <p>
          The App is provided "as is" without any warranties. We shall not be liable for any indirect, incidental, special, consequential or punitive damages.
        </p>

        <h2>7. Contact Information</h2>
        <p>
          If you have any questions about these Terms, please contact us at support@tattoogen.com.
        </p>
      </div>
    </div>
  );
}
