export default function PrivacyPage() {
  return (
    <div className="container mx-auto px-4 py-32 max-w-3xl">
      <h1 className="text-4xl font-bold mb-8 text-foreground">Privacy Policy</h1>
      <div className="prose prose-neutral dark:prose-invert max-w-none text-foreground/80">
        <p className="text-sm text-muted-foreground mb-8">Last Updated: {new Date().toLocaleDateString()}</p>

        <p className="mb-6">
          Welcome to Tattoo Generator ("Company", "we", "our", "us"). We respect your privacy and are committed to protecting your personal data. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you visit our website and use our mobile application (collectively, the "Service").
        </p>
        <p className="mb-6">
          By accessing or using our Service, you signify that you have read, understood, and agree to our collection, storage, use, and disclosure of your personal information as described in this Privacy Policy and our Terms of Service.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4 text-foreground">1. Information We Collect</h2>
        
        <h3 className="text-xl font-medium mt-6 mb-2 text-foreground">1.1 Personal Data</h3>
        <p className="mb-4">
          While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you ("Personal Data"). Personally identifiable information may include, but is not limited to:
        </p>
        <ul className="list-disc pl-6 mb-4 space-y-2">
          <li>Email address</li>
          <li>First name and last name</li>
          <li>Cookies and Usage Data</li>
          <li>Payment information (processed securely by our third-party payment processors)</li>
        </ul>

        <h3 className="text-xl font-medium mt-6 mb-2 text-foreground">1.2 Usage Data</h3>
        <p className="mb-4">
          We may also collect information that your browser sends whenever you visit our Service or when you access the Service by or through a mobile device ("Usage Data").
        </p>
        <p className="mb-4">
          This Usage Data may include information such as your computer's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
        </p>

        <h3 className="text-xl font-medium mt-6 mb-2 text-foreground">1.3 Uploaded Content & AI Generations</h3>
        <p className="mb-4">
          When you upload images to our Service for tattoo generation, style transfer, or AR try-on features, we collect and process these images. We also collect the text prompts you input and the resulting images generated by our AI.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4 text-foreground">2. How We Use Your Information</h2>
        <p className="mb-4">
          We use the collected data for various purposes, primarily to provide and maintain our Service. Specifically, we use your data to:
        </p>
        <ul className="list-disc pl-6 mb-4 space-y-2">
          <li>To provide and maintain our Service, including monitoring the usage of our Service.</li>
          <li>To manage your account and registration as a user of the Service.</li>
          <li>To improve our AI models and algorithms. You acknowledge and agree that we may use your anonymized inputs and generated outputs to train, fine-tune, and improve our machine learning models.</li>
          <li>To contact you regarding updates, security alerts, and administrative messages.</li>
          <li>To provide customer support.</li>
          <li>To monitor the usage of the Service and detect, prevent and address technical issues.</li>
        </ul>

        <h2 className="text-2xl font-semibold mt-8 mb-4 text-foreground">3. Retention of Data</h2>
        <p className="mb-4">
          We will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4 text-foreground">4. Transfer of Data</h2>
        <p className="mb-4">
          Your information, including Personal Data, may be transferred to — and maintained on — computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from your jurisdiction.
        </p>
        <p className="mb-4">
          Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4 text-foreground">5. Disclosure of Data</h2>
        <p className="mb-4">
          We may disclose your Personal Data in the good faith belief that such action is necessary to:
        </p>
        <ul className="list-disc pl-6 mb-4 space-y-2">
          <li>To comply with a legal obligation.</li>
          <li>To protect and defend the rights or property of the Company.</li>
          <li>To prevent or investigate possible wrongdoing in connection with the Service.</li>
          <li>To protect the personal safety of users of the Service or the public.</li>
          <li>To protect against legal liability.</li>
        </ul>

        <h2 className="text-2xl font-semibold mt-8 mb-4 text-foreground">6. Security of Data</h2>
        <p className="mb-4">
          The security of your data is important to us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security. We shall not be liable for any unauthorized access to your data that occurs despite our reasonable security measures.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4 text-foreground">7. Service Providers</h2>
        <p className="mb-4">
          We may employ third party companies and individuals to facilitate our Service ("Service Providers"), to provide the Service on our behalf, to perform Service-related services or to assist us in analyzing how our Service is used. These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4 text-foreground">8. Links to Other Sites</h2>
        <p className="mb-4">
          Our Service may contain links to other sites that are not operated by us. If you click on a third party link, you will be directed to that third party's site. We strongly advise you to review the Privacy Policy of every site you visit. We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4 text-foreground">9. Children's Privacy</h2>
        <p className="mb-4">
          Our Service does not address anyone under the age of 18 ("Children"). We do not knowingly collect personally identifiable information from anyone under the age of 18. If you are a parent or guardian and you are aware that your Children has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from children without verification of parental consent, we take steps to remove that information from our servers.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4 text-foreground">10. Changes to This Privacy Policy</h2>
        <p className="mb-4">
          We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page. You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4 text-foreground">11. Contact Us</h2>
        <p className="mb-4">
          If you have any questions about this Privacy Policy, please contact us via email at: legal@tattoogen.com
        </p>
      </div>
    </div>
  );
}
